### ISSUE TITLE
"help" should show you the contents of {henzell_help[1]}

### ISSUE THREAD

**Issue by vimpulse** [greensnark/dcss_sequell#26]
Thank you for writing/maintaining Henzell; it's a very useful bot.

I just wrote a factoid named [henzell_help\[1\]](http://crawl.develz.org/info/inline.php?q=henzell_help). (As of 9 February 2013, the factoid is too new to be visible when you click that link.)

And now for my feature request:

Typing `Henzell: help` should produce precisely the same output as typing `??henzell_help[1]`.

**Comment by greensnark** [comment]
Done.
